---
title: "Upper San Juan USGS Streamflow + SNOTEL Data Pull"
author: "Lydia Bleifuss"
date: "5/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r Packages, echo = FALSE}
#USGS
library(dataRetrieval)

#SNOTEL
library(RNRCS)

#Other 
library(tidyverse)
library(ggplot2)
library(leaflet)
library(dplyr)
library(maps)
library(lubridate)
library(janitor)
library(tsibble)
library(snakecase)
library(stringr)
library(paletteer)
library(feasts)
library(sf)
library(ggmap)
library(tmap)
library(rgdal)
library(here)
library(kableExtra)
library(inlmisc)
library(ggrepel)
library(gghighlight)

#Spatial Clipping 
library(USAboundaries) # Download shape files
library(USAboundariesData)
```


```{r, echo = FALSE}


#####**HUC USGS locator map:** https://water.usgs.gov/wsc/map_index.html

#####**HUC 8 Data Basin locator map:** https://databasin.org/maps/df7fa3b1a0cc4ee997a677a29b6e9523/active
###**Functions/Data Types/Information Available**

# NWIS
# - readNWISdv | NWIS daily data
# - readNWISqw | 	NWIS water quality data
# - readNWISuv | NWIS instantaneous value data
# - readNWISrating | NWIS rating table for active streamgage
# - readNWISmeas | 	NWIS surface-water measurements
# - readNWISpeak | NWIS peak flow data
# - readNWISgwl | 	NWIS groundwater level measurements
# - readNWISuse | NWIS water use
# - readNWISstat | NWIS statistical service
# - readNWISpCode | NWIS parameter code information
# - readNWISsite | NWIS site information
# - whatNWISsites | NWIS site search using user-specified queries
# - whatNWISdata | NWIS data availability, including period of record and count
# - readNWISdata | NWIS data using user-specified queries

```


```{r AR Graph Theme , echo = FALSE }

theme_ar = function(base_size = 12, base_family = "Avenir") {
  theme_grey(base_size = base_size, base_family = base_family) %+replace%
    theme(
      
      # Specify axis options
      axis.line = element_line(),  
      axis.text.x = element_text(size = base_size*0.8, color = "black", lineheight = 0, angle = 45),  
      axis.text.y = element_text(size = base_size*0.8, color = "black", lineheight = 0),  
      #axis.ticks = element_line(color = "black", size  =  0.2),  
      axis.title.x = element_text(size = base_size, color = "black", margin = margin(0, 10, 0, 0)),  
      axis.title.y = element_text(size = base_size, face = "bold", color = "black", angle = 90, margin = margin(0, 10, 0, 0)),  
      #axis.ticks.length = unit(0.3, "lines"), 
      
      # Specify legend options
      legend.background = element_rect(color = "NA", fill = NA),  
      legend.key = element_rect(color = NA,  fill = NA),  
      #legend.key.size = unit(1.2, "lines"),  
      legend.key.height = NULL,  
      legend.key.width = NULL,      
      legend.text = element_text(size = base_size*0.8, color = "black"),  
      legend.title = element_text(size = base_size*0.8, face = "bold", hjust = 0, color = "black"),  
      #legend.position = "bottom",  
      legend.text.align = NULL,  
      legend.title.align = NULL,  
      #legend.direction = "horizontal",  
      legend.box = NULL, 
      
      # Specify panel options
      panel.background = element_rect(fill = NA, color  =  NA),  
      panel.border = element_rect(fill = NA, color = NA),  
      panel.grid.major = element_line(color = NA),  
      panel.grid.minor = element_line(color = NA),  
      panel.spacing = unit(0, "lines"),   
      
      # Specify facetting options
      strip.background = element_rect(fill = "grey30", color = "grey10"),  
      strip.text.x = element_text(size = base_size*0.8, color = "black"),  
      strip.text.y = element_text(size = base_size*0.8, color = "black",angle = -90),  
      
      # Specify plot options
      plot.background = element_rect(color = NA, fill = NA),  
      plot.title = element_text(size = base_size*1.2, color = "black", face = "bold", margin=margin(0,0,5,0)),  
      plot.subtitle = element_text(size = base_size*0.9, color = "black"),
      plot.margin = unit(rep(1, 4), "lines")
    )
}

```


```{r huc maps examples, echo = FALSE}

  #https://waterdata.usgs.gov/blog/beyond-basic-mapping/
  
  #https://waterdata.usgs.gov/blog/inlmiscmaps/

#View(palettes_c_names)
#ggsave("your_title.pdf", device=cairo_pdf, width = 6, height = 6)
```


```{r Upper San Juan USGS AVAILABLE, echo = FALSE }

#Get to know what data is available in the watershed

sj_available_data <- whatNWISdata(huc = '14080101') #HUC 8 for Upper San Juan 

#comment(sj_available_data) #defines all column heading included in teh dataset 

sj_dis_sites <- sj_available_data %>% 
  #filter(site_tp_cd == "ST") %>%  #ST for stream
  filter(parm_cd == "00060") %>% 
  mutate(guage_type = "Streamflow") %>% 
  distinct(site_no, .keep_all = TRUE)

#Now if we want to specify search, specify by param in the watershed 

#Search params: https://nwis.waterdata.usgs.gov/usa/nwis/pmcodes

#Useful params: 
# Discharge, mean daily (cfs) | 00060
# Discharge, instantaneous (cfs) | 00061
# Precipitation total (in) | 00045

#Exploring Discharge Specifically: 

#dis_codes <- parameterCdFile[grep("discharge", parameterCdFile$parameter_nm, ignore.case = TRUE),] 
#pulling all params that have to do with discharge

#nrow(dis_codes) #There are 24 different params for discharge
#unique(dis_codes$parameter_units) #what are the units? 

kable_usj_sites <- sj_dis_sites %>% 
  select(station_nm, site_no, dec_lat_va, dec_long_va, guage_type) %>% 
  rename(Station = station_nm, Site_No = site_no, Latitude = dec_lat_va, Longitude = dec_long_va, Gauge_Type = guage_type) %>% 
  mutate(Station = str_to_title(Station))

kable_sj <- kable(head(kable_usj_sites, 10)) %>% 
  kable_styling(bootstrap_options = c("striped", 
                                      "hover",
                                      "condensed",
                                      "bordered",
                                      "responsive",
                                      full_widge = F,
                                      position = "left",
                                      position = "float_right",
                                      font_size = 10,
                                      fixed_thead = T)) %>% 
  column_spec(1,width = "20em", bold = T, border_right = T) %>% 
  pack_rows("Upper San Juan Streamflow Gauges (10)", 1, 10, label_row_css = "background-color: #666; color: #fff;") %>% 
  scroll_box(width = "600px", height = "300px") %>% 
  footnote(general = "Here is an example of information we can pull from USGS and then either use for analysis/graphing/mapping in R, or export into an Excel document. We could also put together summary statistics in a talbe like this for streamflow, snowpack, etc.")

kable_sj

```


```{r Upper San Juan USGS PULL ONE GUAGE, echo = FALSE }
#SAN JUAN RIVER AT PAGOSA SPRINGS, CO

sjp_site_no <- "09342500"
sjp_pcode <- "00060" #discharge
sjp_start_date <- "2009-10-01"
sjp_end_date <- "2019-09-30"

sj_pagosa <- readNWISuv(siteNumbers = sjp_site_no, #uv is calling for instantaneous data
                     parameterCd = sjp_pcode,
                     startDate = sjp_start_date,
                     endDate = sjp_end_date)

#IMPORTANT: 
#Column names for discharge and discharge code are read in as "X_00060_00011"  and  "X_00060_00011_cd" 
#names(sj_pagosa)

#To clean up these columns (should alwasy do this for consistency)
sj_pagosa <- renameNWISColumns(sj_pagosa)
#names(sj_pagosa)
#Now these columns are "Flow_Inst" and "Flow_Inst_cd" 


#There are also several attributes attached to each dataframe you pull in, to access these: 
#names(attributes(sj_pagosa))

#To access these attributes, such as the url to the well, see example below: 
url <- attr(sj_pagosa, "url")

#Site info
sjp_site <- attr(sj_pagosa, "siteInfo") %>% 
  mutate(station_nm = str_to_title(station_nm))
  
#Parameter info
sjp_parameter <- attr(sj_pagosa, "variableInfo")

#Join site info with discharge data to create full tidy df

sjp_dis_join <- full_join(sjp_site, sj_pagosa, by = "site_no") %>% 
  select(station_nm, 
         site_no, 
         dec_lat_va, 
         dec_lon_va, 
         hucCd, 
         dateTime, 
         Flow_Inst, 
         Flow_Inst_cd) %>% 
  rename(station_nm = station_nm, 
         site_no = site_no, 
         latitude = dec_lat_va, 
         longitude = dec_lon_va, 
         huc = hucCd, 
         dateTime = dateTime, 
         Flow_Inst = Flow_Inst, 
        Flow_Inst_cd = Flow_Inst_cd) %>% 
  mutate(date = as.Date.POSIXct(dateTime)) %>% #need to seperate date from time, so can find average daily cfs, and plot that
  mutate(year_month = yearmonth(date)) %>%  
  mutate(month = month(date)) %>% 
  mutate(year = year(date)) %>% 
  #mutate(average = mean(Flow_Inst)) %>% 
  group_by(year_month) %>% 
  mutate(average_month_dis = mean(Flow_Inst)) %>% 
  mutate(average_month_dis = round(average_month_dis, 0)) %>% 
  distinct(year_month, .keep_all = TRUE) %>% 
  select(-dateTime, -Flow_Inst)

```


```{r Upper San Juan USGS GRAPH, echo = FALSE}

#Basic graph to get a sense for things: 

sjp_dis_graph <- ggplot(data = sjp_dis_join,
                        aes(date, 
                            average_month_dis)) +
  geom_line() +
  theme_ar() +
  xlab("") +
  ylab("Streamflow (cfs)") +
  ggtitle("San Juan River at Pagosa Springs, CO") +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_date(date_breaks = "1 year",
               date_labels = "%Y",
               expand = expansion()
               ) +
    gghighlight::gghighlight(year %in% 2018) +
  labs(caption = "\nAverage monthly streamflow in the Upper San Juan River near Pagosa Springs, CO from 2009 - 2019.\nFor the purposes of this example, 2018 is highlighted as a drought year.")
  
  
sjp_dis_graph

```

```{r Upper San Juan USGS SEASON GRAPH, echo = FALSE}

# Coerce to a tsibble:
sjp_auto <- as_tsibble(sjp_dis_join, index = year_month) %>% 
  tsibble::fill_gaps()

sjp_seasonal <- sjp_auto %>% 
  feasts::gg_season(average_month_dis) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b", #codes from abrivs https://rdrr.io/r/base/strptime.html
               expand = expansion()
               ) +
  xlab("\nMonth") +
  ylab("Average Monthly Streamflow (cfs)") +
  labs(title = "Upper San Juan Seasonal Streamflow",
       subtitle = "USGS Guage at Pagosa Springs, CO (2009 - 2019)\n") +
  theme(plot.title = element_text(vjust = 0.5)) +
  theme_ar()

sjp_seasonal
```


```{r Upper San Juan USGS MONTH GRAPH, echo = FALSE}

sjp_subseries <- sjp_auto %>% #Great graphical exploration, provides mean for each month across all months. 
  feasts::gg_subseries(average_month_dis) +
  xlab("\nMonth") +
  ylab("Average Streamflow (cfs)\n") +
  ggtitle("Average Streamflow Across all Years (2009 - 2019)\nUSGA Gauge, Pagosa Springs, CO\n") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank())+
  scale_x_date(date_breaks = "120 months",
               date_labels = "%M")

sjp_subseries
```

**I pulled all SNOTEL sites using a NRCS R package. We can pull data from and map any of these gauges.**
```{r Upper San Juan SNOTEL PULL, echo = FALSE }

sjp_snotel_data <- grabNRCS.elements(site_id = "SNTL:840")


meta_snotel <- grabNRCS.meta(ntwrks = "SNTL", cnvrt.elev = FALSE)


meta_snotel_df <- as.data.frame(meta_snotel[['SNTL']]) %>% 
  select(-ts, -ntwk, -wyear) %>% 
  rename(State = state, Site = site_name, Start_Date = start, End_Date = enddate, Lat = latitude, Long = longitude, Elevation_ft = elev_ft, County = county, HUC = huc, Site_ID = site_id) %>% 
  arrange(-desc(State))


kable_snotel <- kable(meta_snotel_df) %>% 
 kable_styling(bootstrap_options = c("striped", 
                                     "bordered",
                                      "hover",
                                      "condensed",
                                      "responsive",
                                      full_widge = F,
                                      position = "left",
                                      position = "float_right",
                                      font_size = 10,
                                      fixed_thead = T)) %>% 
  column_spec(1,20, width = "20em", bold = T, border_right = T) %>% 
  scroll_box(width = "800px", height = "300px") 

kable_snotel

```

```{r, echo = FALSE}
sjp_snotel <- grabNRCS.data(network = "SNTL", 
                            site_id = 840, 
                            timescale = "daily", 
                            DayBgn = "2009-10-01", 
                            DayEnd = "2050-09-30") %>% 
  select(Date, Snow.Water.Equivalent..in..Start.of.Day.Values) %>% 
  rename(Snow_Water_Equivalent = Snow.Water.Equivalent..in..Start.of.Day.Values) %>% 
  mutate(date = as.Date.character(Date)) 

sjp_snotel_clean <- sjp_snotel %>%  
mutate(year_month = yearmonth(date)) %>%  
  mutate(month = month(date)) %>% 
  mutate(year = year(date)) %>% 
  group_by(year_month) %>% 
  mutate(mean_month_swe = mean(Snow_Water_Equivalent)) %>% 
 mutate(mean_month_swe = round(mean_month_swe, 0)) %>% 
   mutate(daily_swe_round = round(Snow_Water_Equivalent, 0)) %>% 
  distinct(year_month, .keep_all = TRUE)

df_max_point <- sjp_snotel_clean %>% 
  mutate(group_all = "group_all") %>% 
  group_by(group_all) %>% 
  filter(year_month == max(year_month))

sjp_snotel_hist <- sjp_snotel_clean %>%
  mutate(group_all = "group_all") %>% 
  group_by(group_all) %>% 
  mutate(max_year = max(year)) %>% 
  filter(year < max_year)

sjp_snotel_hist_max <- sjp_snotel_clean %>%
  mutate(group_all = "group_all") %>% 
  group_by(group_all) %>% 
  mutate(max_year = max(year)) %>% 
  filter(year >= max_year)

```

```{r Upper San Juan SNOTEL GRAPH, echo = FALSE }
# #View(palettes_c_names)
# 
# #df <- data.frame(year = c(2020))
# 
# 
# sjp_swe_seasonal <- ggplot() +
#   # geom_line(data = sjp_snotel_hist, 
#   #           aes(x = month,
#   #               y = mean_month_swe, 
#   #               group = year, 
#   #               color = year), 
#   #           alpha = 0.8, size = 0.8) +
#   geom_line(data = sjp_snotel_2020, 
#             linetype = "dashed", 
#             size = 1, 
#             aes(x = month, 
#                 y = mean_month_swe))+
# geom_text_repel(
#     data = subset(sjp_snotel_2020, month == max(month)),
#     aes(label = paste(year_month)),
#     size = 6,
#     nudge_x = 45,
#     segment.color = NA
#   )+
# # annotate(
# #     geom = "curve", x = 7, y = 15, xend = 5.2, yend = 13.5,
# #     curvature = .3, arrow = arrow(length = unit(3, "mm"))
# #   ) +
# #   annotate(geom = "text", x = 7, y = 15, label = "2020", hjust = "left") +
# #   theme_ar()+
#   labs(title = "Average Monthly Snow-Water-Equivalent, Pagosa Springs, CO",
#         subtitle = "NCRS SNOTEL Guage 840 (2009 - 2020)\n")+
#   xlab("\nMonth") +
#   ylab("Average Monthly SWE (in)\n") +
#   guides(color=guide_legend("Year")) +
#   scale_y_continuous(expand = c(0,0)) +
#  scale_x_discrete(expand = c(0,0), 
#                   limits=c(10,11,12,1,2,3,4,5,6,7,8,9)) +
#   theme(axis.text.x = element_text(angle = 0)) +
#   scale_color_paletteer_c("ggthemes::Temperature Diverging")
# 
# 
# 
# sjp_swe_seasonal
```

```{r Upper San Juan SNOTEL GRAPH TEST, echo = FALSE }

sjp_swe_seasonal_test <- ggplot() +
   geom_line(data = sjp_snotel_hist, 
             aes(x = month, 
                 y = mean_month_swe, 
                 group = year, 
                 color = year)) +
   geom_line(data = sjp_snotel_hist_max, 
             linetype = "dashed", 
            size = 1,
             aes(x = month, 
                 y = mean_month_swe, 
                 group = year)) +
  geom_point(data = df_max_point, 
             aes(x = month, 
                 y = mean_month_swe)) +
geom_text_repel(data = df_max_point, 
                aes(month, mean_month_swe, 
                    label = year),
                point.padding = 0.9,
    nudge_x = 3,
    nudge_y = 4,
    segment.curvature = -1e-20,
    arrow = arrow(length = unit(0.03, "npc"))
  ) +
  labs(title = "Average Monthly Snow-Water-Equivalent, Pagosa Springs, CO",
        subtitle = "NCRS SNOTEL Guage 840 (2009 - 2020)\n")+
  xlab("\nMonth") +
  ylab("Average Monthly SWE (in)\n") +
  guides(color=guide_legend("Year")) +
  scale_y_continuous(expand = c(0,0)) +
 scale_x_discrete(expand = c(0,0),
                  limits=c(10,11,12,1,2,3,4,5,6,7,8,9)) +
  theme_ar() +
  theme(axis.text.x = element_text(angle = 0)) +
  scale_color_paletteer_c("ggthemes::Temperature Diverging")


sjp_swe_seasonal_test

```




```{r, echo = FALSE}
# set.seed(42)
# ggplot(Orange, aes(age, circumference, color = Tree)) +
#   geom_line() +
#   coord_cartesian(xlim = c(min(Orange$age), max(Orange$age) + 90)) +
#   geom_text_repel(
#     data = subset(Orange, age == max(age)),
#     aes(label = paste("Tree", Tree)),
#     size = 6,
#     nudge_x = 45,
#     segment.color = NA
#   ) +
#   theme_classic(base_size = 16) +
#   theme(legend.position = "none") +
#   labs(title = "Orange Trees", x = "Age (days)", y = "Circumference (mm)")
# 
# #View(Orange)
```

```{r Upper San Juan STATS - DECOMP, echo = FALSE }
#average snowpack year, deviation above and below? 

#USGS Stats Code: https://help.waterdata.usgs.gov/code/stat_cd_nm_query?stat_nm_cd=%25&fmt=html

```

```{r Upper San Juan SHPS, echo = FALSE }

#can I load all huc8s? 
# huc8 <- read_sf(dsn = "HUC8_US.shp",
#                  layer = "HUC8_US") %>% 
#               st_transform(crs = 4326) %>% 
#plot(huc8)


#checking out USJ huc 8
USJ_HUC8<- read_sf(dsn = "HUC8_US.shp",
                 layer = "HUC8_US") %>% 
              st_transform(crs = 4326) %>% 
  filter(HUC8 == 14080101) %>% 
  select(HUC8, NAME)
#plot(usj_huc8)

#NM and CO .shp files
State <- us_states(resolution = "high", states = NULL) %>%  
  st_transform(crs = 4326) %>% 
  select(name)

#All discharge sites into .shp
USJ_Discharge_Sites <- st_as_sf(sj_dis_sites, 
                                coords = c("dec_long_va",
                                           "dec_lat_va"), 
                                crs = 4326) %>% 
  select(agency_cd, site_no, station_nm, guage_type) %>% 
  rename(Agency = agency_cd, Site = site_no, Station_Info = station_nm, Gauge_Type = guage_type) %>% 
   mutate(Station_Info = str_to_title(Station_Info))


#Main discharge site
USJ_Pagosa_Springs <- st_as_sf(sjp_site, 
                                coords = c("dec_lon_va",
                                           "dec_lat_va"), 
                                crs = 4326) %>% 
  select(agency_cd, site_no, station_nm) %>% 
  rename(Agency = agency_cd, Site = site_no, Station_Info = station_nm) %>% 
   mutate(Gauge_Type = "Streamflow")


# #All Snotel Sites
# snotel_shp <- st_as_sf(meta_snotel_df, 
#                                 coords = c("Long",
#                                            "Lat"), 
#                                 crs = 4326) 
# 
# #Snotel in USJ (840)
# USJ_Snotel <- st_intersection(snotel_shp, USJ_HUC8)


```
  
  
  
  
**A quick map with the Upper San Juan HUC 8, the USGS Streamflow gauge at Pagosa Springs (grey) and all other USGS streamflow gauges in the Upper San Juan (blue). You can click on the gauge dots for more information.**
```{r Upper San Juan TMAP, echo = FALSE }

tmap_mode("view") #Set so the map will be interactive.

usj_huc8_map <- tm_basemap("Esri.WorldImagery") + #Add a basemap explored previously in mapview.
    tm_layout("Upper San Juan Streamflow Stations") +
  tm_shape(USJ_HUC8) +
  tm_fill("NAME",
          col = "sienna2",
          legend.show = FALSE,
          alpha = 0.4,
          id = "NAME") +
  tm_shape(State) +
  tm_borders("white") +
  tm_fill(fill = NA,
          alpha = 0,
          id = "name") +
  tm_shape(USJ_Discharge_Sites)+
  tm_dots(col = "cornflowerblue",
          size = 0.1) +
  # tm_shape(USJ_Discharge_Sites)+
  # tm_markers(shape = marker_icon,
  #            markers.on.top.of.text = TRUE,
  #            text.just = "top") +
  tm_shape(USJ_Pagosa_Springs)+
  tm_dots(col = "grey",
          size = 0.2,
          id = "Station_Info") +
  tm_minimap(toggle = T)

usj_huc8_map

```

```{r, echo = FALSE}

# library(leaflet)
# 
# data(USJ_Dicharge_Sites)
# leaflet() %>% 
# 	addTiles() %>% 
# 	addMapPane("overlay03", zIndex = 403) %>% 
# 	addMarkers(data = USJ_Discharge_Sites,
# 			   icon = list(), 
# 			   options = markerOptions(pane="overlay03"))
```

